version: '3.9'
services:
  app:
   # image: "klinkby/booqr-app:4"
    build: ..
    ports:
      - "8080:8080/tcp"
    read_only: true
    tmpfs:
      - "/tmp:mode=1777"
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://127.0.0.1:8080/" ]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "64M"
