version: '3.9'
services:
  app:
    # image: "klinkby/booqr-app:4"
    build: ..
    read_only: true
    tmpfs:
      - "/tmp:mode=1777,noexec,nosuid"
    volumes:
      - app-sock:/var/run/lighttpd
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "test -S /var/run/lighttpd/sock" ]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "64M"

volumes:
  app-sock:
