services:
  app:
    build: ..
    read_only: true
    tmpfs:
      - '/tmp:mode=1777,noexec,nosuid'
    volumes:
      - './app_sock:/var/run/lighttpd'
    cap_drop:
      - ALL
    security_opt:
      - 'no-new-privileges:true'
    restart: unless-stopped
    network_mode: none
    healthcheck:
      test:
        - CMD-SHELL
        - test -S /var/run/lighttpd/sock
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 64M
